### ISSUE TITLE
possible memory leak

### ISSUE THREAD

**Issue by nek0** [isovector/ecstasy#9]
Hi Sandy,

I am currently using ecstasy in an [ongoing game project](https://github.com/nek0/tracer) and while profiling it I found that ecstasy might leak memory when setting components. I enclose two profiling outputs:
[tracer-game.hc.pdf](https://github.com/isovector/ecstasy/files/2011079/tracer-game.hc.pdf)
[tracer-game.hy.pdf](https://github.com/isovector/ecstasy/files/2011080/tracer-game.hy.pdf)

Thanks for your time and effort

**Comment by isovector** [comment]
Hiya!

I noticed the same leak, and I think it's patched in [0.2.1.0](https://hackage.haskell.org/package/ecstasy). There's some annoying renames from 0.1.* to 0.2.*, but only because I named them terribly to begin with. if you don't feel like dealing with breaking library changes, i can backport them to 0.1.1.0.

If you are OK upgrading (you get [virtual components](https://hackage.haskell.org/package/ecstasy-0.2.1.0/docs/Data-Ecstasy.html#world)!), it's mostly:

* `s/get/query/`
* `s/newEntity/createEntity/`
* `s/defEntity'/unchanaged/`
* `s/defEntity/newEntity/`
* `s/defWorld/defStorage/`
* `s/emap/emap allEnts/`
* `s/efor/efor allEnts/`

Thanks for reaching out! Now that I know I'm not the only user, I'll be less insane with my maintenance strategy.

**Comment by isovector** [comment]
Just cut a [0.1.1.1 release](https://hackage.haskell.org/package/ecstasy-0.1.1.1); pretty sure it will get rid of the memory leak you're seeing! Closing this, but feel free to reopen!

**Comment by nek0** [comment]
thanks. updating to >=0.2 did the charm.
